name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  compile:
    name: "compile ${{ matrix.test }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          - test_action
          - test_display

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install ESPHome
        run: pip install -r requirements.txt

      - name: Cache PlatformIO packages
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: pio-esp32s2-idf-${{ hashFiles(format('tests/{0}.yaml', matrix.test)) }}
          restore-keys: pio-esp32s2-idf-

      - name: Compile
        run: esphome compile tests/${{ matrix.test }}.yaml
